---
- name: Configure NTPD to start under ntp user ownership (sysconfig)
  lineinfile:
    dest: /etc/sysconfig/ntpd
    regexp: '^#?OPTIONS='
    line: OPTIONS="-u ntp:ntp"
  notify: restart ntpd service
- name: configure ntp restrictions
  lineinfile:
    dest: /etc/ntp.conf
    line: restrict -6 default kod nomodify notrap nopeer noquery
  notify: restart ntpd service
...
